export const hairstyleDataMen = [
  { id: 1, label: 'Afro' },
  { id: 2, label: 'UnderCut' },
  { id: 3, label: 'Pompadour' },
  { id: 4, label: 'SlickBack' },
  { id: 5, label: 'CurlyShag' },
  { id: 6, label: 'WavyShag' },
  { id: 7, label: 'FauxHawk' },
  { id: 8, label: 'Spiky' },
  { id: 9, label: 'CombOver' },
  { id: 10, label: 'HighTightFade' },
  { id: 11, label: 'ManBun' },
  { id: 12, label: 'Afro' },
  { id: 13, label: 'LowFade' },
  { id: 14, label: 'UndercutLongHair' },
  { id: 15, label: 'TwoBlockHaircut' },
  { id: 16, label: 'TexturedFringe' },
  { id: 17, label: 'BluntBowlCut' },
  { id: 18, label: 'LongWavyCurtainBangs' },
  { id: 19, label: 'MessyTousled' },
  { id: 20, label: 'MediumLengthWavy' },
  { id: 21, label: 'CornrowBraids' },
  { id: 22, label: 'LongHairTiedUp' },
  { id: 23, label: 'Middle-parted' },
];
export const hairstyleDataFemale = [
  { id: 1, label: 'ShortPixieWithShavedSides' },
  { id: 2, label: 'ShortNeatBob' },
  { id: 3, label: 'DoubleBun' },
  { id: 4, label: 'Updo' },
  { id: 5, label: 'Spiked' },
  { id: 6, label: 'bowlCut' },
  { id: 7, label: 'Chignon' },
  { id: 8, label: 'PixieCut' },
  { id: 9, label: 'SlickedBack' },
  { id: 10, label: 'LongCurly' },
  { id: 11, label: 'CurlyBob' },
  { id: 12, label: 'StackedCurlsInShortBob' },
  { id: 13, label: 'SidePartCombOverHairstyleWithHighFade' },
  { id: 14, label: 'WavyFrenchBobVibesfrom1920	' },
  { id: 15, label: 'BobCut' },
  { id: 16, label: 'ShortTwintails' },
  { id: 17, label: 'ShortCurlyPixie' },
  { id: 18, label: 'LongStraight' },
  { id: 19, label: 'LongWavy' },
  { id: 20, label: 'FishtailBraid' },
  { id: 21, label: 'Ponytail' },
  { id: 22, label: 'Dreadlocks' },
  { id: 23, label: 'Cornrows' },
  { id: 24, label: 'ShoulderLengthHair' },
  { id: 25, label: 'LooseCurlyAfro' },
  { id: 26, label: 'LongTwintails' },
  { id: 27, label: 'LongHimeCut' },
  { id: 28, label: 'BoxBraids' },
];

export const hairColor = [
    { id:1, label: 'blonde' },
    { id:2, label: 'platinumBlonde	' },
    { id:3, label: 'brown' },
    { id:4, label: 'lightBrown' },
    { id:5, label: 'blue' },
    { id:6, label: 'lightBlue' },
    { id:7, label: 'purple' },
    { id:8, label: 'lightPurple' },
    { id:9, label: 'pink' },
    { id:10, label: 'black' },
    { id:11, label: 'white' },
    { id:12, label: 'grey' },
    { id:13, label: 'silver' },
    { id:1, label: 'red' },
    { id:15, label: 'orange' },
    { id:1, label: 'green' },
    { id:1, label: 'gradient' },
    { id:18, label: 'multicolored' },
    { id:19, label: 'darkBlue' },
    { id:20, label: 'burgundy' },
    { id:21, label: 'darkGreen' },
   
];