import React from 'react'
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coilycue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">

      <body className={inter.className}>

      <div className="w-screen ">
      <Navbar />
      </div>

        {children}

        </body>

    </html>
  );
}
